id: P7444D484
initial_creation_type: ocr
source_metadata:
  volumes:
    4a64b6d8d2a34aa89f387af63a565dc3:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ཁྱད་པར་དུ་འཕགས་པའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
