id: DCA7E0001
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-27T08:25:03+00:00'
last_modified: '2022-06-07T07:10:43.304605+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    dd5d:
      image_group_id: I1PD95846
      title: ཁྱད་པར་དུ་འཕགས་པའི་བསྟོད་པ།
      total_pages: 1539
      order: 1
      base_file: dd5d.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
